### ISSUE TITLE
v0.31 KeyError: 'download_action' in console log when updated from older version

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_uuunyaa_tools#16]
v0.31で以下のエラーが発生します。
機能的な不備はすみませんが何が正しいのかわからないので未確認です。
（asset search からダウンロード、インポートは問題なくできます）

blender 2.92/ windows 10

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 187, in reload
    self.add(_Utilities.from_dict(asset))
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 88, in from_dict
    download_action=asset['download_action'],
KeyError: 'download_action'
ContentCache.__init__: cache_folder=C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache, temporary_dir=C:\Users\xxx\AppData\Local\Temp\tmpczfd8g86
_load_contents: 37 from C:\Users\a\AppData\Local\Temp\mmd_uuunyaa_tools_cache\contents.json

KeyError: 'download_action'

**Comment by UuuNyaa** [comment]
報告ありがとうございます。
このエラーはassets.jsonのフォーマット変更が原因です。
古いフォーマットのassets.jsonが残っていると、このエラーを出力して無視します。

UuuNyaa Assets OperatorパネルからUpdate Assets JSONとDelete Debug Asset JSONを実行して、古いフォーマットのJSONを削除してみてください。

![image](https://user-images.githubusercontent.com/70152495/112069000-5dd8ed00-8bae-11eb-9442-cfd0f939d320.png)

Thanks for the report.
This error is caused by the format change of assets.json.
If you still have the old format assets.json, then it will output this error and ignore the json.

Please try Update Assets JSON and Delete Debug Asset JSON from the UuuNyaa Assets Operator panel to remove the old format JSON.

**Comment by listelin** [comment]
ありがとうございます。
上記手順（Update Assets JSONとDelete Debug Asset JSONを実行）により、エラーが解消することを確認しました。
