### ISSUE TITLE
blender_mmd_tools本体への統合の予定は？

### ISSUE THREAD

**Issue by Bancho29** [UuuNyaa/blender_mmd_uuunyaa_tools#60]
UuuNyaa様、初めまして。

blender_mmd_toolsもsugiany版、powroupi版を経て、
UuuNyaa様のフォーク版が事実上の本家になりそうですが、
blender_mmd_uuunyaa_toolsをblender_mmd_tools本体へ
統合する予定はありますでしょうか？

**Comment by UuuNyaa** [comment]
@Bancho29 
次のような機能の棲み分けを考えています。
- blender_mmd_tools
  - MMDモデル・モーション・ポーズのインポート/エクスポート機能
  - MMD規格内での編集機能
- blender_mmd_uuunyaa_tools
  - それ以外のMMD機能

あなたはどう思いますか？


I am thinking of the following segregation of features.
- blender_mmd_tools
  - Import/export features of MMD models, motions, and poses
  - Editing features within the MMD specification
- blender_mmd_uuunyaa_tools
  - Other MMD features

What do you think?

**Comment by Bancho29** [comment]
返事が遅れて申し訳ありません。

自分的にはやっぱり統合すべきだと考えますが、
他の利用者はどう考えてますでしょうか？

**Comment by listelin** [comment]
私はどちらかといえば別々のほうがいいと思います。

UuuNyaa Toolsは、そもそもMMDとは関係のない機能も多く入っています。

1　MMDモデルをBlenderで作成・修正するための機能
　→　MMD TOOLS (import/export　及び付随機能)

２　Blender上でMMDモデル・モーションを便利に利用するための機能
　・Rigify統合、リジッドボディのクロス化、ピラミッドクロス、・・・

３　Blender用の機能（必ずしもMMDでなくても使える機能）
　・Eevee設定、パフォーマンスチェック、照明プリセット（UuuNyaa照明）、
　　UuuNyaa Sky、UuuNyaaマテリアル、マテリアルAdjuster、・・・

統合すれば、初めて利用する人には少し分かりやすいかもしれませんが、それ以上のメリットはない気がします。

コアのMMD TOOLSは分離したままの方が、将来的に他の人がメンテナーになるハードルが随分減りますし、
統合のためにコード修正する労力をかけるなら新しい機能を作ったほうがいいとも思います。

細かく言えば、機能的には少し整理する余地があるかもしれません。
例えばマテリアルをCycles用に変換は、MMD ToolsではなくUuuNyaa Toolsに移動したほうがスッキリする、とか
MMD DisplayがなぜかMiscタブにあるのをMMDタブに移して、MMD物理の可視性制御とマージする、とか
更には本来可視性制御はNメニュータブではなく、ヘッダーにあったほうがよいのでは、など
＊これが優先順位が高いというわけではなく、例として上げただけです。

強く統合すべきでないと思っているわけではなく、どちらかといえば、という程度ですが私の考えは以上です。

---

I think I would rather have them separate.

UuuNyaa Tools contains a lot of functions that have nothing to do with MMD.

1 Functions for creating and modifying MMD models in Blender
　→ MMD TOOLS (import/export and related functions)
2 Features for convenient use of MMD models and motions in Blender
　Rigify integration, rigid body crossing, pyramid crossing, ...

3 Features for Blender (not necessarily MMD)
　Eevee settings, performance check, lighting presets (UuuNyaa lighting)
　　UuuNyaa Sky, UuuNyaa Material, Material Adjuster, ...

Integration might make things a little easier to understand for new users, but I don't think it would be any more beneficial.

Keeping the core MMD tools separate would greatly reduce the hurdle for others to become maintainers in the future.
I also think it would be better to create a new feature if UuuNyaa have to spend the effort to modify the code for the integration.

In terms of details, the functionality could use a little tidying up.
For example, the conversion of materials to Cycles could be moved to UuuNyaa Tools instead of MMD Tools, which would be cleaner.
MMD Display is somehow in the Misc tab, but it could be moved to the MMD tab and merged with the MMD physics visibility control.
Furthermore, the visibility control should be in the header, not in the N menu tab.
I'm not saying that this is a high priority, but it's just an example.

I'm not saying that I don't think it should be integrated strongly, just that I think it should be more or less, but that's my opinion.

**Comment by UuuNyaa** [comment]
@Bancho29 @listelin 
意見ありがとうございます。
統合のメリットを実感するまでは、分離したままで開発を進めようと思います。

Thanks for your opinion.
Until I see the benefits of integration, I will continue to develop in isolation.

**Comment by Bancho29** [comment]
かなり遅くなりましたが
UuuNyaa様におまかせしたいと思います
