### ISSUE TITLE
MMD to rigify error

### ISSUE THREAD

**Issue by unicornetto** [UuuNyaa/blender_mmd_uuunyaa_tools#81]
![rigify error](https://user-images.githubusercontent.com/40151773/179427914-ff0c5f6d-a9f7-43f2-899a-a4321cb25c06.png)

Hi, I tried to convert from MMD to rigify, but I get these errors. I think some are for bone naming but it also failed to to open the Rig Shaper ibrary. I'm using version 0.7.1 of MMD tools.

I've also tried 3 different models, errors are the same all the time.

**Comment by listelin** [comment]
I assume you manually code > zip downloaded and extracted it to the following folder
D:\programs\Blender\2.92\scripts\addons\
That won't work because the necessary files are missing.

Also, the version of mmd_tools is outdated.

1. delete the following folders
D:\programs\Blender\2.92\scripts\addons\mmd_uuunyaa_tools
D:\programs\Blender\2.92\scripts\addons\mmd__tools

2. download the following zip file and zip install it from Preferences>Add-ons
https://github.com/UuuNyaa/blender_mmd_tools/releases/tag/v2.4.0

3. download the following zip file and zip install it from Preferences>Add-ons
https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/releases/tag/v1.4.0
